/**
 * Stable, machine-readable error codes. Clients switch on these, never on
 * message text, so messages can be reworded freely.
 */
export enum ErrorCode {
  // generic
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  FORBIDDEN = 'FORBIDDEN',
  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL = 'INTERNAL',
  MAINTENANCE = 'MAINTENANCE',

  // auth
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  OTP_INVALID = 'OTP_INVALID',
  OTP_EXPIRED = 'OTP_EXPIRED',
  OTP_TOO_MANY_ATTEMPTS = 'OTP_TOO_MANY_ATTEMPTS',
  EMAIL_NOT_SENT = 'EMAIL_NOT_SENT',
  SOCIAL_TOKEN_INVALID = 'SOCIAL_TOKEN_INVALID',
  ACCOUNT_BANNED = 'ACCOUNT_BANNED',
  UNDERAGE = 'UNDERAGE',
  PROFILE_INCOMPLETE = 'PROFILE_INCOMPLETE',
  SIGNUPS_CLOSED = 'SIGNUPS_CLOSED',

  // staff (admin panel)
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  TWO_FACTOR_INVALID = 'TWO_FACTOR_INVALID',
  TWO_FACTOR_SETUP_REQUIRED = 'TWO_FACTOR_SETUP_REQUIRED',
  PASSWORD_CHANGE_REQUIRED = 'PASSWORD_CHANGE_REQUIRED',

  // wallet
  INSUFFICIENT_COINS = 'INSUFFICIENT_COINS',
  INSUFFICIENT_GEMS = 'INSUFFICIENT_GEMS',
  ALREADY_CLAIMED = 'ALREADY_CLAIMED',
  DAILY_LIMIT_REACHED = 'DAILY_LIMIT_REACHED',
  CASHOUT_BELOW_MINIMUM = 'CASHOUT_BELOW_MINIMUM',
  /** Selfie verification needed before this cash-out (monthly limit). */
  KYC_REQUIRED = 'KYC_REQUIRED',
  AD_NOT_VERIFIED = 'AD_NOT_VERIFIED',

  // payments
  PAYMENT_DECLINED = 'PAYMENT_DECLINED',
  PAYMENT_ACTION_REQUIRED = 'PAYMENT_ACTION_REQUIRED',
  UNKNOWN_PRODUCT = 'UNKNOWN_PRODUCT',

  // social
  BLOCKED = 'BLOCKED',
  NOT_FRIENDS = 'NOT_FRIENDS',
  NEVER_MATCHED = 'NEVER_MATCHED',
  /** Too many new follows today (economy rule maxFollowsPerDay). */
  FOLLOW_LIMIT = 'FOLLOW_LIMIT',

  // matching
  NOT_IN_MATCH = 'NOT_IN_MATCH',
  SKIP_COOLDOWN = 'SKIP_COOLDOWN',
  PARTNER_UNAVAILABLE = 'PARTNER_UNAVAILABLE',
  MATCHING_PAUSED = 'MATCHING_PAUSED',
}
