/**
 * Material icon names that draw a Solar glyph instead (480 Design,
 * CC BY 4.0 — https://www.figma.com/community/file/1166831539721848736),
 * the same icons the Flutter app uses through `solar_icons`.
 *
 * Each glyph is a file in public/icons/solar/<name>-<b|o>.svg (b = Bold,
 * o = Outline), fetched only when used and cached by the browser. The value
 * pins one style regardless of the Icon's variant: line-like glyphs
 * (arrows, chevrons, "…_outline" names) are always Outline, dot menus
 * always Bold; null follows the variant. Generated from @iconify-json/solar.
 */
export const SOLAR: Record<string, "b" | "o" | null> = {
  account_balance: null, // solar:banknote
  account_balance_wallet: null, // solar:wallet
  add_circle_outline: "o", // solar:add-circle
  add_photo_alternate: null, // solar:gallery-add
  alt_route: null, // solar:routing-2
  arrow_back: "o", // solar:arrow-left
  arrow_drop_down: "o", // solar:alt-arrow-down
  arrow_forward: "o", // solar:arrow-right
  badge: null, // solar:user-id
  bedtime: null, // solar:moon-sleep
  block: null, // solar:forbidden-circle
  blur_on: null, // solar:radial-blur
  bolt: null, // solar:bolt
  call: null, // solar:phone
  call_end: null, // solar:end-call-rounded
  call_split: null, // solar:routing
  cameraswitch: null, // solar:camera-rotate
  campaign: null, // solar:hand-money
  card_giftcard: null, // solar:gift
  casino: null, // solar:gamepad-minimalistic
  chat: null, // solar:chat-round-dots
  chat_bubble: null, // solar:chat-round-dots
  chat_bubble_outline: "o", // solar:chat-round-dots
  check_circle: null, // solar:check-circle
  chevron_right: "o", // solar:alt-arrow-right
  child_care: null, // solar:smile-circle
  cloud_off: null, // solar:cloud-cross
  compare_arrows: "o", // solar:transfer-horizontal
  content_copy: null, // solar:copy
  copy: null, // solar:copy
  credit_card: null, // solar:card
  delete_outline: "o", // solar:trash-bin-minimalistic
  description: null, // solar:document-text
  do_not_disturb_on: null, // solar:minus-circle
  download: null, // solar:download-minimalistic
  edit: null, // solar:pen
  emoji_events: null, // solar:cup-star
  error_outline: "o", // solar:danger-circle
  expand_more: "o", // solar:alt-arrow-down
  face: null, // solar:smile-circle
  fast_forward: null, // solar:rewind-forward
  favorite: null, // solar:heart
  favorite_border: "o", // solar:heart
  female: null, // solar:women
  flag: null, // solar:flag
  forum: null, // solar:dialog-2
  group: null, // solar:users-group-rounded
  group_add: null, // solar:user-plus-rounded
  history: null, // solar:history
  hourglass_bottom: null, // solar:hourglass
  hourglass_top: null, // solar:hourglass
  how_to_reg: null, // solar:user-check-rounded
  inbox: null, // solar:inbox
  info_outline: "o", // solar:info-circle
  insights: null, // solar:graph-up
  interests: null, // solar:widget-4
  ios_share: null, // solar:export
  key: null, // solar:key
  link: "o", // solar:link-round
  local_fire_department: null, // solar:fire
  local_pizza: null, // solar:donut-bitten
  lock: null, // solar:lock-keyhole
  lock_open: null, // solar:lock-keyhole-unlocked
  lock_outline: "o", // solar:lock-keyhole
  login: null, // solar:login-2
  logout: null, // solar:logout-2
  mail_outline: "o", // solar:letter
  male: null, // solar:men
  manage_accounts: null, // solar:user-id
  mark_email_read: null, // solar:letter-opened
  mark_email_unread: null, // solar:letter-unread
  military_tech: null, // solar:medal-ribbon-star
  monetization_on: null, // solar:dollar
  more_horiz: "b", // solar:menu-dots
  more_vert: "b", // solar:menu-dots
  no_adult_content: null, // solar:forbidden
  notifications_active: null, // solar:bell-bing
  notifications_none: "o", // solar:bell
  open_in_browser: null, // solar:square-arrow-right-up
  open_in_new: null, // solar:square-arrow-right-up
  outlined_flag: "o", // solar:flag
  paid: null, // solar:dollar
  pause: null, // solar:pause
  pause_circle: null, // solar:pause-circle
  payments: null, // solar:banknote-2
  people_alt: null, // solar:users-group-two-rounded
  percent: null, // solar:sale
  person: null, // solar:user-rounded
  person_add: null, // solar:user-plus-rounded
  person_add_alt_1: null, // solar:user-plus-rounded
  person_off: null, // solar:user-cross-rounded
  person_outline: "o", // solar:user-rounded
  person_search: null, // solar:magnifier
  phone_iphone: null, // solar:smartphone
  photo: null, // solar:gallery
  photo_camera: null, // solar:camera
  photo_camera_front: null, // solar:camera-minimalistic
  photo_library: null, // solar:gallery-wide
  play_arrow: null, // solar:play
  play_circle: null, // solar:play-circle
  public: null, // solar:global
  qr_code_2: null, // solar:qr-code
  receipt_long: null, // solar:bill-list
  record_voice_over: null, // solar:user-speak-rounded
  redeem: null, // solar:gift
  refresh: "o", // solar:refresh
  remove_circle_outline: "o", // solar:minus-circle
  replay: "o", // solar:restart
  rotate_left: "o", // solar:undo-left-round
  rotate_right: "o", // solar:undo-right-round
  schedule: null, // solar:clock-circle
  self_improvement: null, // solar:meditation-round
  send: null, // solar:plain
  settings: null, // solar:settings
  share: null, // solar:share
  shield: null, // solar:shield
  shopping_bag: null, // solar:bag-smile
  skip_next: null, // solar:skip-next
  storefront: null, // solar:bag-smile
  support_agent: null, // solar:headphones-round
  swap_horiz: "o", // solar:transfer-horizontal
  timer_off: null, // solar:alarm-turn-off
  toll: null, // solar:wallet-money
  tune: null, // solar:tuning-2
  verified: null, // solar:verified-check
  verified_user: null, // solar:shield-check
  videocam: null, // solar:videocamera
  visibility: null, // solar:eye
  visibility_off: null, // solar:eye-closed
  warning_amber: null, // solar:danger-triangle
  waving_hand: null, // solar:hand-shake
  wb_sunny: null, // solar:sun
  whatshot: null, // solar:fire
  wifi_off: null, // solar:cloud-cross
  workspace_premium: null, // solar:crown
};
