/**
 * In-call icebreaker prompts. Light and safe for strangers: no dating,
 * sex, politics, religion or anything that asks for personal details.
 */
export type GameId = 'wyr' | 'this_or_that' | 'questions';
export const GAME_IDS: readonly GameId[] = ['wyr', 'this_or_that', 'questions'];

export interface Prompt {
  text: string;
  /** Two choices for wyr / this_or_that; absent for questions. */
  options?: [string, string];
}

const wyr = (a: string, b: string): Prompt => ({ text: 'Would you rather…', options: [a, b] });
const tot = (a: string, b: string): Prompt => ({ text: 'This or that?', options: [a, b] });

export const PROMPTS: Record<GameId, readonly Prompt[]> = {
  wyr: [
    wyr('Be able to fly', 'Be invisible'),
    wyr('Live by the beach', 'Live in the mountains'),
    wyr('Only eat biryani forever', 'Only eat pizza forever'),
    wyr('Talk to animals', 'Speak every language'),
    wyr('Travel to the past', 'Travel to the future'),
    wyr('Never use social media again', 'Never watch a movie again'),
    wyr('Have a rewind button', 'Have a pause button'),
    wyr('Always be 10 minutes late', 'Always be 20 minutes early'),
    wyr('Be famous', 'Be rich but unknown'),
    wyr('Live without music', 'Live without movies'),
    wyr('Have super strength', 'Have super speed'),
    wyr('Explore space', 'Explore the deep ocean'),
    wyr('Read minds', 'See the future'),
    wyr('Be a great singer', 'Be a great dancer'),
    wyr('Have a pet dragon', 'Have a pet unicorn'),
    wyr('Win the lottery', 'Live twice as long'),
    wyr('Never feel cold again', 'Never feel hot again'),
    wyr('Be the funniest person in the room', 'Be the smartest'),
    wyr('Only travel by train', 'Only travel by plane'),
    wyr('Have unlimited chai', 'Have unlimited coffee'),
    wyr('Live in a big city', 'Live in a small village'),
    wyr('Be a famous athlete', 'Be a famous actor'),
    wyr('Know every recipe', 'Know every song'),
    wyr('Teleport anywhere', 'Pause time for an hour a day'),
    wyr('Give up your phone for a month', 'Give up sweets for a year'),
    wyr('Have a personal chef', 'Have a personal driver'),
    wyr('Watch only comedies', 'Watch only thrillers'),
    wyr('Be a superhero', 'Be a wizard'),
    wyr('Always know the time', 'Always know the direction'),
    wyr('Live in a treehouse', 'Live in a houseboat'),
    wyr('Never wait in a queue again', 'Never be stuck in traffic again'),
    wyr('Be great at every sport', 'Be great at every instrument'),
    wyr('Have endless free flights', 'Have endless free food'),
    wyr('Meet your favourite celebrity', 'Meet your great-great-grandparents'),
    wyr('Live without the internet', 'Live without air conditioning'),
    wyr('Be able to breathe underwater', 'Be able to see in the dark'),
    wyr('Have a photographic memory', 'Be able to forget anything you want'),
    wyr('Spend a day in a video game', 'Spend a day in a cartoon'),
    wyr('Only whisper', 'Only shout'),
    wyr('Eat dessert first', 'Skip dessert forever'),
    wyr('Wake up at 5 am every day', 'Go to bed at 3 am every day'),
    wyr('Have a robot helper', 'Have a talking pet'),
  ],
  this_or_that: [
    tot('Tea', 'Coffee'),
    tot('Cats', 'Dogs'),
    tot('Beach', 'Mountains'),
    tot('Sunrise', 'Sunset'),
    tot('Books', 'Movies'),
    tot('Summer', 'Winter'),
    tot('Pizza', 'Burger'),
    tot('Cricket', 'Football'),
    tot('Netflix', 'YouTube'),
    tot('Early bird', 'Night owl'),
    tot('Sweet', 'Spicy'),
    tot('Texting', 'Calling'),
    tot('City', 'Countryside'),
    tot('Android', 'iPhone'),
    tot('Rain', 'Sunshine'),
    tot('Chocolate', 'Vanilla'),
    tot('Road trip', 'Flight'),
    tot('Gaming', 'Reading'),
    tot('Breakfast', 'Dinner'),
    tot('Comedy', 'Horror'),
    tot('Biryani', 'Karahi'),
    tot('Gym', 'Yoga'),
    tot('Instagram', 'TikTok'),
    tot('Podcasts', 'Music'),
    tot('Stay in', 'Go out'),
    tot('Sneakers', 'Sandals'),
    tot('Samosa', 'Pakora'),
    tot('Mango', 'Strawberry'),
    tot('Dance', 'Sing'),
    tot('Board games', 'Video games'),
    tot('Hoodie', 'Jacket'),
    tot('Ice cream', 'Cake'),
    tot('Planner', 'Go with the flow'),
    tot('Window seat', 'Aisle seat'),
    tot('Superheroes', 'Wizards'),
    tot('Fries', 'Onion rings'),
    tot('Photos', 'Videos'),
    tot('Bike', 'Car'),
    tot('Old songs', 'New songs'),
    tot('Lassi', 'Milkshake'),
    tot('Space', 'Ocean'),
    tot('Popcorn', 'Nachos'),
  ],
  questions: [
    { text: "What's the best thing that happened to you this week?" },
    { text: 'If you could live anywhere in the world, where would it be?' },
    { text: "What's a song you can't stop listening to?" },
    { text: "What's your comfort food?" },
    { text: "What's a skill you'd love to learn?" },
    { text: "What's the best trip you've ever taken?" },
    { text: 'What would your perfect weekend look like?' },
    { text: "What's a movie you could watch again and again?" },
    { text: 'If you had a free day tomorrow, what would you do?' },
    { text: "What's something that always makes you laugh?" },
    { text: "What's a hobby you got into recently?" },
    { text: 'Which fictional world would you like to visit?' },
    { text: "What's the best advice you've ever been given?" },
    { text: "What's on your bucket list?" },
    { text: "What's your favourite way to relax?" },
    { text: "What's a small thing that makes your day better?" },
    { text: 'If you could have dinner with anyone, who would it be?' },
    { text: "What's the most interesting place you've been to?" },
    { text: 'What app do you use the most?' },
    { text: "What's a food you'd never try again?" },
    { text: "What's your go-to karaoke song?" },
    { text: "What's something you're proud of?" },
    { text: 'If you could master one instrument, which one?' },
    { text: "What's your favourite season and why?" },
    { text: 'Which superpower would be the most useful day to day?' },
    { text: "What's a game you loved as a kid?" },
    { text: "What's the last thing that made you really happy?" },
    { text: 'What would you name a pet dragon?' },
    { text: "What's a city you want to visit next?" },
    { text: 'Are you a planner or spontaneous?' },
    { text: "What's the best gift you've ever received?" },
    { text: 'What would you do with an extra hour every day?' },
    { text: "What's your favourite thing about where you live?" },
    { text: "What's a show you'd recommend to everyone?" },
    { text: "What's your dream job, if money didn't matter?" },
    { text: "What's something new you tried this year?" },
    { text: 'Which emoji do you use the most?' },
    { text: "What's your favourite festival or holiday?" },
    { text: 'If you wrote a book, what would it be about?' },
    { text: "What's the most fun you've had recently?" },
    { text: 'Mountains, sea or desert for your next holiday?' },
    { text: "What's a talent you have that people don't expect?" },
  ],
};

/** A random prompt index not used yet in this match (cycles once all are used). */
export function pickPrompt(game: GameId, used: number[], rand: () => number = Math.random): number {
  const all = PROMPTS[game].length;
  const seen = new Set(used);
  const free = Array.from({ length: all }, (_, i) => i).filter((i) => !seen.has(i));
  const pool = free.length ? free : Array.from({ length: all }, (_, i) => i);
  return pool[Math.floor(rand() * pool.length)];
}
